### PR TITLE
🐛 fix #203 assert failFast config is a boolean

### LINKED ISSUE #203: [bug] failFast configuration parameter should fail if an invalid value is provided
**Describe the bug**
It seems that it is possible to configure Testy with an invalid value for the `failFast` configuration parameter, and it does not cause a failure.

**Version(s) affected**

**To Reproduce**

Run any suite with the following configuration in `.testyrc.json`:

```json
{
  "directory": "./tests",
  "filter": ".*_test.js$",
  "language": "en",
  "failFast": "I AM AN INVALID VALUE",
  "randomOrder": true
}
```

**Expected behavior**
An error message before running any suite explaining that the provided value is not valid, and the allowed values are `true` and `false` (booleans).

### PR DESCRIPTION
**Pull request by ignacio-r**
Fix #203 Failfast configuration must be a valid boolean.

### CODE REVIEW

**Comment by ignacio-r** [comment]
Hi @ngarbezza do you think these changes and tests are sufficient? Let me know if you'd like me to change anything

**Comment by ngarbezza** [comment]
Thanks for the fix @ignacio-r ! Changes look great. There are some lint errors you can fix with the `lint:fix` task. Could you please correct them?

**Comment by ngarbezza** [comment]
@all-contributors please add @ignacio-r as a contributor for code and tests

**Comment by ignacio-r** [comment]
Sure, I'll fix them

**Review by ngarbezza — APPROVED** [review]

**Comment by ngarbezza** [comment]
@all-contributors please add @ignacio-r as a contributor for code and tests

**Comment by ngarbezza** [comment]
@all-contributors please add @ignacio-r as a contributor for code and tests

**Pull request merged**
